// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionProcess.Infrastructure.Data;

#nullable disable

namespace TransactionProcess.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241030224002_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransactionProcess.Core.Entities.TransactionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TransactionRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "1234",
                            Amount = 1000.00m,
                            CreateDate = new DateTime(2024, 10, 30, 22, 40, 1, 843, DateTimeKind.Utc).AddTicks(1489),
                            CreateUser = "testuser",
                            CurrencyCode = "USD",
                            Status = "A",
                            TransactionDate = new DateTime(2024, 2, 20, 12, 33, 16, 0, DateTimeKind.Unspecified),
                            TransactionId = "Invoice0000001"
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "5678",
                            Amount = 300.00m,
                            CreateDate = new DateTime(2024, 10, 30, 22, 40, 1, 843, DateTimeKind.Utc).AddTicks(1500),
                            CreateUser = "testuser",
                            CurrencyCode = "EUR",
                            Status = "R",
                            TransactionDate = new DateTime(2024, 2, 21, 2, 4, 59, 0, DateTimeKind.Unspecified),
                            TransactionId = "Invoice0000002"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
