// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionProcess.Infrastructure.Data;

#nullable disable

namespace TransactionProcess.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241031123412_seed_data")]
    partial class seed_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransactionProcess.Core.Entities.TransactionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TransactionRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "1234",
                            Amount = 1000.00m,
                            CreateDate = new DateTime(2024, 10, 31, 12, 34, 11, 971, DateTimeKind.Utc).AddTicks(3678),
                            CreateUser = "testuser",
                            CurrencyCode = "USD",
                            Status = "A",
                            TransactionDate = new DateTime(2024, 2, 20, 12, 33, 16, 0, DateTimeKind.Unspecified),
                            TransactionId = "Invoice0000001"
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "5678",
                            Amount = 300.00m,
                            CreateDate = new DateTime(2024, 10, 31, 12, 34, 11, 971, DateTimeKind.Utc).AddTicks(3688),
                            CreateUser = "testuser",
                            CurrencyCode = "EUR",
                            Status = "R",
                            TransactionDate = new DateTime(2024, 2, 21, 2, 4, 59, 0, DateTimeKind.Unspecified),
                            TransactionId = "Invoice0000002"
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "2345",
                            Amount = 500.00m,
                            CreateDate = new DateTime(2024, 10, 31, 12, 34, 11, 971, DateTimeKind.Utc).AddTicks(3695),
                            CreateUser = "testuser",
                            CurrencyCode = "GBP",
                            Status = "D",
                            TransactionDate = new DateTime(2024, 3, 1, 14, 23, 10, 0, DateTimeKind.Unspecified),
                            TransactionId = "Invoice0000003"
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = "6789",
                            Amount = 1200.00m,
                            CreateDate = new DateTime(2024, 10, 31, 12, 34, 11, 971, DateTimeKind.Utc).AddTicks(3701),
                            CreateUser = "testuser",
                            CurrencyCode = "USD",
                            Status = "A",
                            TransactionDate = new DateTime(2024, 3, 10, 10, 30, 5, 0, DateTimeKind.Unspecified),
                            TransactionId = "Invoice0000004"
                        },
                        new
                        {
                            Id = 5,
                            AccountNumber = "3456",
                            Amount = 750.00m,
                            CreateDate = new DateTime(2024, 10, 31, 12, 34, 11, 971, DateTimeKind.Utc).AddTicks(3708),
                            CreateUser = "testuser",
                            CurrencyCode = "CAD",
                            Status = "R",
                            TransactionDate = new DateTime(2024, 4, 15, 18, 45, 25, 0, DateTimeKind.Unspecified),
                            TransactionId = "Invoice0000005"
                        },
                        new
                        {
                            Id = 6,
                            AccountNumber = "7890",
                            Amount = 200.00m,
                            CreateDate = new DateTime(2024, 10, 31, 12, 34, 11, 971, DateTimeKind.Utc).AddTicks(3714),
                            CreateUser = "testuser",
                            CurrencyCode = "AUD",
                            Status = "D",
                            TransactionDate = new DateTime(2024, 5, 20, 8, 15, 30, 0, DateTimeKind.Unspecified),
                            TransactionId = "Invoice0000006"
                        },
                        new
                        {
                            Id = 7,
                            AccountNumber = "4567",
                            Amount = 950.00m,
                            CreateDate = new DateTime(2024, 10, 31, 12, 34, 11, 971, DateTimeKind.Utc).AddTicks(3720),
                            CreateUser = "testuser",
                            CurrencyCode = "EUR",
                            Status = "A",
                            TransactionDate = new DateTime(2024, 6, 12, 11, 25, 45, 0, DateTimeKind.Unspecified),
                            TransactionId = "Invoice0000007"
                        },
                        new
                        {
                            Id = 8,
                            AccountNumber = "8901",
                            Amount = 1300.00m,
                            CreateDate = new DateTime(2024, 10, 31, 12, 34, 11, 971, DateTimeKind.Utc).AddTicks(3726),
                            CreateUser = "testuser",
                            CurrencyCode = "JPY",
                            Status = "R",
                            TransactionDate = new DateTime(2020, 7, 5, 9, 50, 10, 0, DateTimeKind.Unspecified),
                            TransactionId = "Invoice0000008"
                        },
                        new
                        {
                            Id = 9,
                            AccountNumber = "5670",
                            Amount = 450.00m,
                            CreateDate = new DateTime(2024, 10, 31, 12, 34, 11, 971, DateTimeKind.Utc).AddTicks(3737),
                            CreateUser = "testuser",
                            CurrencyCode = "INR",
                            Status = "D",
                            TransactionDate = new DateTime(2005, 8, 14, 16, 40, 0, 0, DateTimeKind.Unspecified),
                            TransactionId = "Invoice0000009"
                        },
                        new
                        {
                            Id = 10,
                            AccountNumber = "2341",
                            Amount = 1600.00m,
                            CreateDate = new DateTime(2024, 10, 31, 12, 34, 11, 971, DateTimeKind.Utc).AddTicks(3743),
                            CreateUser = "testuser",
                            CurrencyCode = "CHF",
                            Status = "A",
                            TransactionDate = new DateTime(1999, 9, 22, 6, 10, 50, 0, DateTimeKind.Unspecified),
                            TransactionId = "Invoice0000010"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
